spring:
  application:
    name: Personal_blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: '0514'

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
